### ISSUE TITLE
Please update description

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/universal-analytics#24]
Can someone with permission change the description to read:

A complete GWT wrapper for Google Universal Analytics.

**Comment by olafleur** [comment]
Like that? @christiangoudreau I think you should also give the rights on universal-analytics to @rdwallis

**Comment by christiangoudreau** [comment]
He already has... :D

**Comment by rdwallis** [comment]
I think I've got all rights except I can't update settings on the Repo.  So I can overwrite master but I can't change the description :D

**Comment by rdwallis** [comment]
Actually sorry I meant the github description.

**Comment by rdwallis** [comment]
@christiangoudreau for this I meant the github project description.  Only an admin can change it.

**Comment by christiangoudreau** [comment]
Try again, I've added you to our manager group

**Comment by rdwallis** [comment]
Cheers thanks
