### ISSUE TITLE
Automatic tracking of pages not implemented?

### ISSUE THREAD

**Issue by confile** [ArcBees/universal-analytics#32]
I did not see any place where the ``NavigationEvent``is tracked so I guess I have to implement a ``GoogleAnalyticsNavigationTracker``my own. Is this correct or did I overlook something?

**Comment by rdwallis** [comment]
Yes see this wiki: https://github.com/ArcBees/universal-analytics/wiki/Automatically-track-pagviews-when-using-GWTP

The gwtp-eclipse-plugin will also create this for you if you create a new project with the Universal Analytics option checked.
