### ISSUE TITLE
Ready for next release?

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/universal-analytics#38]
Think this is ready for a new minor release.

The major worrying feature is the fallback system for when analytics.js fails to load.  It appears to work well for me.

@Chris-V @meriouma @christiangoudreau if you have time can you double check the fallback feature and see if it makes sense and you don't think it will cause sampling bias because it might not track certain info for the fallback users that it will track for others, like whether they're on mobile / desktop.

**Comment by christiangoudreau** [comment]
Oups, you already did :D

**Comment by christiangoudreau** [comment]
I also need a release note and that any documentation that is needed is done before releasing

**Comment by rdwallis** [comment]
### New Features:

In General Options:
  1.  useBeacon(boolean useBeacon)
    * Setting this to true, will instruct the client to use navigator.sendBeacon to send the hit. This is useful in cases where you wish to track an event just before a user navigates away from your site, without delaying the navigation. If the browser does not support navigator.sendBeacon, the hit will be sent normally.
  2. dataSource(String datasource)
    * Indicates the data source of the hit. Hits sent from analytics.js will have data source set to 'web';  hits sent from one of the mobile SDKs will have data source set to 'app'.


Fallback server - See docs

In AnalyticsModuleBuilder:
  1. autoInit(boolean autoInit).
     * Set to false to disable loading analytics.js.  Used if analytics.js is already inserted into the page some other way.

### Fixes:
   Always load analytic.js from https://www.google.com/analytics.js #37 

### Breaking Api Changes:

Traffic**s**ourcesOptions renamed to Traffic**S**ourcesOptions

In AnalyticsOptions:
app**t**rackingOptions() renamed to app**T**rackingOptions();

**Comment by christiangoudreau** [comment]
Thanks, do you want to add task before the release?

**Comment by rdwallis** [comment]
Yes, hold off I'll fix that tomorrow.

On Thu, Jun 18, 2015 at 7:32 PM, christiangoudreau <notifications@github.com

**Comment by 0mega** [comment]
Hi everyone,
Is there any estimate of when you will be able to make a new release of current master?

Thanks

**Comment by olafleur** [comment]
Closing as the release has been done.
