### ISSUE TITLE
This library needs tests!

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/universal-analytics#41]
Really important but I don't have time to do this.  This is a hard library to test because it is so interwoven with analytics.js.

Need to test: 

client side analytics on web and in native apps.

Server side analytics / with and without a client generated cookie.

Fallback server.

Any volunteers?

**Comment by tbroyer** [comment]
Glancing at the code, I'm also surprised of seeing `HashMap`s as static state on the server without any synchronization! Possibly not worth opening an issue if it's not a problem in practice, but related to needing some more testing (even though such things would be hard to test)

**Comment by rdwallis** [comment]
@tbroyer can you look at #44 and see if it improves things.  Don't often write multithreaded code would appreciate a review.

**Comment by rdwallis** [comment]
@tbroyer #45 should fix things.  But it'll be a few days before I can actually run the code. Please review.

**Comment by rdwallis** [comment]
Closing this issue because it's not going to be fixed.

Full testing will require automatically logging events and then connecting to google analytics and checking if those events were recorded correctly.  So think it's beyond our resources.

Reopen if you're willing to setup a testing platform.   Otherwise think maybe integrating this into carstore would be a good idea.
