### ISSUE TITLE
Tasks are not currently supported

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/universal-analytics#5]
analytics.js has a [tasks feature](https://developers.google.com/analytics/devguides/collection/analyticsjs/tasks).

I think this allows you to hook into analytics commands so that for example you can make calls ping your own server as well as the Google ones.

I don't think these are very useful but just thought I'd mention that they're missing.

**Comment by yarcub** [comment]
This feature is a must have to cordova/phonegap developers.

To be compatible with phonegap/cordova, the `checkProtocolTask` must be disabled or all requests to GA will be aborted.
https://developers.google.com/analytics/devguides/collection/analyticsjs/tasks

See http://www.blastam.com/blog/index.php/2013/07/ga-universal-analytics-phonegap-mobile-apps

**Comment by yarcub** [comment]
@rdwallis could you give some guidelines to contribute to this feature?

**Comment by olafleur** [comment]
Closing, as this issue is more than a year old. Feel free to reopen if you still have the issue with the current version.
